name: MRO on MySQL

on:
  push:
  workflow_dispatch:

jobs:
  test_mysql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Start MySQL
        run: docker-compose -f ./tests/mysql/docker-compose.yml up -d
      - name: Wait for MySQL to be ready
        run: |
          service_name=$(docker-compose -f ./tests/mysql/docker-compose.yml ps -q db)
          while [ "$(docker inspect -f '{{.State.Health.Status}}' $service_name)" != "healthy" ]; do
            echo "Waiting for MySQL to become healthy..."
            sleep 2
          done

      # debugging
      - name: Check MySQL Logs
        run: docker logs $(docker-compose -f ./tests/mysql/docker-compose.yml ps -q db)
      - name: Verify MySQL Container Status
        run: docker-compose -f ./tests/mysql/docker-compose.yml ps
      - name: Print PWD
        run: pwd

      - name: Install Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm run test-mysql

      # debugging ls
      - name: List files
        run: ls -al
      