name: Run simulated database tests on MySQL

on:
  push:
  workflow_dispatch:

jobs:
  test_mysql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          sudo pip3 install docker-compose
      - name: Start MySQL
        run: docker-compose -f tests/mysql/docker-compose.yml up -d
      - name: Wait for MySQL to be ready
        run: |
          while [ "$(docker inspect -f '{{.State.Health.Status}}' tests_mysql_1)" != "healthy" ]; do
            echo "Waiting for MySQL to become healthy..."
            sleep 2
          done
          
