name: Run simulated database tests on SQLite

on:
  push:
  workflow_dispatch:

jobs:
  test_sqlite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start SQLite
        run: echo "Ready to test"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install --include=dev
      - name: Run SQLite Tests
        run: npx mocha 'tests/sqlite/**/*.test.js'